### ISSUE TITLE
stardist-napari on an offline workstation

### ISSUE THREAD

**Issue by haesleinhuepf** [stardist/stardist-napari#1]
Hi all,

I'm just installing napari on an offline-workstation. Those machines unfortunately exist quite a lot in local light microscopy facilities. Napari works well if I copy the installation directory with all installed plugins on the other computer. However, when running stardist, it tries to download models, which is obviously not possible on this offline machine. Can you give me instructions of which folder I need to copy over where stardist stores the models locally?

Thanks!

Best,
Robert

**Comment by uschmidt83** [comment]
Hi Robert,

you can find out to which folder the models have been downloaded (the location varies based on operating system):

```python
>>> from stardist import models
>>> model = models.StarDist2D.from_pretrained('2D_versatile_fluo')
Found model '2D_versatile_fluo' for 'StarDist2D'.
Downloading data from https://github.com/stardist/stardist-models/releases/download/v0.1/python_2D_versatile_fluo.zip
5324800/5320433 [==============================] - 0s 0us/step
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.479071, nms_thresh=0.3.

>>> print(model.logdir)
/home/uwe/.keras/models/StarDist2D/2D_versatile_fluo
```

Best,
Uwe

**Comment by haesleinhuepf** [comment]
Hey Uwe,

ahh, it's the ".keras" folder! Thanks! :-)

Cheers,
Robert
