### ISSUE TITLE
stardist-napari requires `tensorflow` but pip doesn't reacognize tensorflow-macos

### ISSUE THREAD

**Issue by psobolewskiPhD** [stardist/stardist-napari#5]
I was reminded about this when I went to update my stardist-napari.
The `setup.py` includes `tensorflow` but on macOS the package is `tensorflow-macos`.
pip doesn't recognize the later as the former and the install/update fails—even though it's imported as `tensorflow`.
Is there a way to flag that? by platform or something? Or maybe remove it?
I do notice that `stardist` doesn't list `tensorflow` as a requirement, but of course it's in the README. Here the situation is different, due to the Plugin menu install...

**Comment by psobolewskiPhD** [comment]
One option is to leave things as are, and rely on the README and napari-hub to provide info regarding installing tensorflow, etc. at first installation.
Then, perhaps the napari devs could provide an option to use `--no-deps` when *updating* a plugin, since presumably the user environment contains the deps?
This would address: https://github.com/stardist/stardist-napari/issues/3 as well I think?

Now obviously a major update that requires an update to the deps would have to provide an error/warning...

**Comment by psobolewskiPhD** [comment]
BTW, why *doesn't* this issue happen with `stardist`?

**Comment by maweigert** [comment]
> BTW, why _doesn't_ this issue happen with `stardist`?

Yes, for this reason regular `stardist` (and its neural network dependency `csbdeep`) doesn't depend on `tensorflow` and requires the user to install an appropriate version of it before. Not really ideal, I know! 😅

**Comment by psobolewskiPhD** [comment]
> Indeed, it seems that platform dependent requirements could be include like so:
> 
> ```
>     install_requires=[
>         'tensorflow;  platform_system!="Darwin" or platform_machine!="arm64"',
>         'tensorflow-macos;  platform_system=="Darwin" and platform_machine=="arm64"',
>     ],
> ```
> 
> But then again, maybe its best to remove tf as explicit dependency altogether...

So I tried this in a local clone (macOS 12, arm64) and it still doesn't install via `pip install -e .` in an env that has `csbdeep` `tensorflow-macos` and `stardist` already, everything functioning. (Nota bene: `pip install stardist -U` JustWorks)
pip finds everything and then decides it needs to downgrade numpy which fails.
☹️ 
`CC=gcc-11 CXX=g++-11 python setup.py install` does work tho, so maybe there is a clue there?
🤷‍♂️

**Comment by maweigert** [comment]
> pip finds everything and then decides it needs to downgrade numpy which fails.
> ☹️

Yes, that is what I recurrenty observe too, most likely due to tensorflow again pinning some old numpy version. Hard to go around that :(

**Comment by uschmidt83** [comment]
> Looks like Apple will continue to maintain `tensorflow-macos` and it has something to do with the GPU aspects. see: https://developer.apple.com/forums/thread/700083?answerId=704971022#704971022

I think we will go for `tensorflow-macos` if Apple is committed to maintain that. The necessary change to setup.py is already part of a [pending PR](https://github.com/stardist/stardist-napari/pull/10/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

**Comment by psobolewskiPhD** [comment]
I wonder if there is any logic that would permit `tensorflow` (e.g. the conda-forge one) on macOS arm64 while at the same time permitting `tensorflow-macos`. 
Also, I have no idea how these names work, after all it's always `import tensorflow ......`

**Comment by maweigert** [comment]
> Also, I have no idea how these names work, after all it's always `import tensorflow ......`

Yes, its complicated :))

Btw, thanks a lot for testing this all out - your image.sc post is my goto reference now :)

**Comment by psobolewskiPhD** [comment]
> Btw, thanks a lot for testing this all out - your image.sc post is my goto reference now :)

Thanks 😊 I wish i could edit that OP to keep it current. 
Maybe I should start a new thread with the latest info condensed together?

**Comment by psobolewskiPhD** [comment]
> > Looks like Apple will continue to maintain `tensorflow-macos` and it has something to do with the GPU aspects. see: https://developer.apple.com/forums/thread/700083?answerId=704971022#704971022
> 
> I think we will go for `tensorflow-macos` if Apple is committed to maintain that. The necessary change to setup.py is already part of a [pending PR](https://github.com/stardist/stardist-napari/pull/10/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

I posted this in the other issue (https://github.com/stardist/stardist-napari/issues/3#issuecomment-1046067077) but Apple has updated the tensorflow-deps conda package, so now it has numpy 1.21. So they are clearing continuing support. Tensorflow-macos just got bumped to 2.8 and tensorflow-metal just got updated too.

**Comment by psobolewskiPhD** [comment]
Another update on the tensorflow/tensorflow-macos issue from an Apple engineer. Good news, they're aware of the issue.

> So here I think the issue is that a lot of the packages that check for Tensorflow do it against the package name reserved for the baseline TensorFlow called tensorflow, whereas the TensorFlow package on MacOS is tensorflow-macos. We are working on a generic solution that will fix this issue but it will take until TF2.9 timeline for that to take effect.


See: https://developer.apple.com/forums/thread/701656?answerId=706752022#706752022

**Comment by psobolewskiPhD** [comment]
Update: tensorflow-macos 2.9 is live, but I don't see any difference in pip behavior.
Anyhow, this issue was resolved by:
https://github.com/stardist/stardist-napari/commit/e91f8065f133e291a77b8f35fdf9f670c097cf1f
Also,

**Comment by psobolewskiPhD** [comment]
Update2: in a conda env (macOS, M1 arm64) with napari, but not having TF:
`mamba create -y -n test-env python=3.9 napari `
You can launch napari from the terminal and use the GUI to install stardist-napari and **IT JUST WORKS**!
🎉 
Y'all are awesome :🤩 
(no `tensorflow-metal` so it's slow, but it works. Maybe add that behind a gate like `tensorflow-macos`? Although `tensorflow-metal` also works on x86 macs with AMD GPU...)
