### ISSUE TITLE
Exporting 3D segmented labels from napari

### ISSUE THREAD

**Issue by Seleit** [stardist/stardist-napari#6]
Hello Stardist team,

I have a quick question that you might be able to help with.

I am running Stardist on a Z-stack in napari and the 3d segmentation results are quite good. I would now like to do some measurements on the segmented nuclei (mean intensity, count etc). For a 2D picture this is easy, i could export the labels as PNG from napari and then add them to the ROI manager in Fiji for example. 

But for the 3D segmented stack i cannot export it as PNG and when i try to export it as TIFF it just shows an empty stack on Fiji.

Is there a way to export stardist segmented 3D nuclear labels from Napari to something that could be used in FIJI for downstream analysis of the segmented labels? Or even better is there a way to extract that data directly from napari?

Thank you !

**Comment by psobolewskiPhD** [comment]
Have you looked at:
https://github.com/haesleinhuepf/napari-skimage-regionprops
I've not used it in 3D, but the gif in the README suggests it should work!
CC: @haesleinhuepf

**Comment by maweigert** [comment]
Was about to say the same! :) Alternatively, saving the layer as tiff should actually work directly from within napari.

**Comment by Seleit** [comment]
Perfect ! The Napari Skimage region props plugin does the trick ! Thank you very much

For some reason the exporting of the selected labels layer as a tiff file does not work. It simply produces an empty stack with no labels when opened in Fiji. Not sure why that is.

Thanks again !

**Comment by uschmidt83** [comment]
> For some reason the exporting of the selected labels layer as a tiff file does not work. It simply produces an empty stack with no labels when opened in Fiji. Not sure why that is.

Are you sure it's empty? Have you adjusted brightness & contrast?

**Comment by Seleit** [comment]
yep, there isn't even any grey values to adjust.

<img width="911" alt="Screenshot 2021-11-18 at 09 56 29" src="https://user-images.githubusercontent.com/65588609/142383837-e7924a6c-ccab-4400-8888-35094dbc16b0.png">

**Comment by uschmidt83** [comment]
Strange. Just tested it, and works for me. One thing you could try is to adjust the datatype (uint16) before saving:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/231996/142403327-6eb6b530-4027-48d7-8701-0202863bd175.png">
